### ISSUE TITLE
Any interest in a PR with fixes?

### ISSUE THREAD

**Issue by gingerbeardman** [jonasgeiler/3d-rasterizer-lua#1]
Hi

Thanks for taking the time to convert this tutorial to Lua. 

I'm going through your code and have found some ~~errors~~ issues with LOVE2D 11. Is there any interest in me forking and filing a PR with the fixes?

Aside: after I've got everything working as intended, I plan to try some optimisations that will hopefully increase speed a little. 

My goal is to use a modified version of this on Playdate with its Lua SDK. 

Let me know your thoughts. Cheers!

**Comment by jonasgeiler** [comment]
It's been a while since I've last written some Lua code and I am pretty certain the code isn't to best - so yeah, feel free to make some changes! I'm glad someone acknowledges my work 😅

The only thing I'd like you to do is put the current code into the `PreviousParts` folder, so you can see the progress along the way!
It was a big part of the fun when I first made this!

Should I add you as a direct collaborator? Or will you be working on your own fork?

**Comment by gingerbeardman** [comment]
I'll work on my own fork for now, keep an eye for a small PR!

Thanks again

**Comment by gingerbeardman** [comment]
Just a small PR so far to get things working in LOVE2D 11.

I also noticed that the flat-colour shading half of Part5 (most useful to me!) is not represented so I am creating that retrospectively.

**Comment by gingerbeardman** [comment]
# Optimisations

## removal of the bitwise operators
it's not really needed. >> 0 is just a C quick shortcut for make a float into an integer, by removing the fractional part of a number. `Math.floor` does the same, and you use that inside the bitwise shift anyway. Removing the bitwise gives a good boost.

## local alias any functions called multiple times
for example in some places, within loops or functions, a function might be called multiple times. Here it's good to set a local variable to the function to speed up repeat accesses. This gives a small boost.
eg. 
```
local qfloor = math.floor
n = qfloor(x) * qfloor(y) * qfloor(z)
```

# FPS

Measured @ 400x240 which is the resolution of Playdate

| Part  | Original  | Optimised  |
|---|---|---|
| 4  | 55 | 60  |
| 5 (flat) | — | 43 |
| 5 (gouraud) | 29 | 35 |
| 6  | 20 | 21 |
| Final  | 29 | 32 |

# Further optimisation plans

## Integer divide by 1
It's often quicker to do `//1` (integer divide by 1) the use `Math.floor` but this modern Lua feature is not supported by LOVE2D.

## Constants
Specifying variables as constants, using `<const>`, if they are not going to be modified often improves performance as Lua can optimise for that behind the scenes. Again, this modern Lua feature is not supported by LOVE2D.

## Drawing triangles natively
For Playdate I plan to draw the triangles natively using the SDK built-in triangle function. Knowing how to draw the triangles by scanline method is cool, but it will be faster using the SDK triangle. 

LOVE2D no longer has triangle command so I am using `love.graphics.polygon`, which gives instant 60fps for flat shaded rendering. There is some extra work needed ([Ordering Tables](http://www.farbrausch.de/~fg/seminars/lightspeed_download.pdf) to replace z-buffer) as you can see the triangles are being drawn in the wrong order.

<img width="400" alt="Screen shot 2021-09-28 at 14 09 51" src="https://user-images.githubusercontent.com/49612/135093245-ecbcbf7a-34af-4b0b-b7e2-5a612320afe3.png">

**Comment by gingerbeardman** [comment]
Added PRs for:

1. Part 5 flat
2. readme change

That's it from me! 

Another PR will come when (if) I add Ordering Tables to a version of Part 5 flat.

Thanks again!
